# Generated by Django 5.1.3 on 2026-06-13 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparacion', 'En Preparación'), ('listo', '¡Listo!'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('mercado_pago_id', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nombre_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_entrega', models.CharField(default='mostrador', max_length=50)),
                ('numero_mesa', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_pago', models.CharField(default='mercadopago', max_length=50)),
                ('impreso_caja', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('telefono', models.CharField(help_text='+541169544042', max_length=20)),
                ('abierto', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('variantes', models.CharField(blank=True, help_text='Ej: Suiza, Gratinada, Fugazzeta, Napolitana', max_length=255, null=True)),
                ('guarniciones', models.CharField(blank=True, help_text='Ej: Puré de Papa, Papas Fritas...', max_length=255, null=True)),
                ('puntos_coccion', models.CharField(blank=True, help_text='Ej: Cocido, Jugoso, A punto', max_length=255, null=True)),
                ('rellenos', models.CharField(blank=True, help_text='Ej: Jamón y queso, Queso solo, Queso y tomate', max_length=255, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='pedidos.categoria')),
                ('puntos_venta', models.ManyToManyField(related_name='productos', to='pedidos.puntoventa')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variante_elegida', models.CharField(blank=True, max_length=100, null=True)),
                ('guarnicion_elegida', models.CharField(blank=True, max_length=100, null=True)),
                ('punto_coccion_elegido', models.CharField(blank=True, max_length=100, null=True)),
                ('relleno_elegido', models.CharField(blank=True, max_length=100, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='punto_venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.puntoventa'),
        ),
    ]
