# Generated by Django 5.1.5 on 2026-06-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='salsa_elegida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='salsas',
            field=models.CharField(blank=True, help_text='Ej: Fileto, Blanca, Bolognesa (+800)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='puntoventa',
            name='telefono',
            field=models.CharField(help_text='1169544042', max_length=20),
        ),
    ]
