# Generated by Django 5.1.5 on 2026-06-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_detallepedido_salsa_elegida_producto_salsas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='precio_extra_salsa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
