# Generated by Django 5.1.5 on 2026-06-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_detallepedido_precio_extra_salsa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='guarniciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='puntos_coccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='rellenos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='variantes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
