# Generated by Django 5.1.3 on 2026-06-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_producto_guarniciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='precio_extra_salsa',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='adicional_elegido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='hielo_elegido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='adicionales',
            field=models.CharField(blank=True, help_text='Ej: Sin Limón, Con Limón (+500) | Normal, Cargado (+1500)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='opcion_hielo',
            field=models.CharField(blank=True, help_text='Ej: Con Hielo, Sin Hielo', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='salsas',
            field=models.CharField(blank=True, help_text='Ej: Fileto, Bolognesa (+800)', max_length=255, null=True),
        ),
    ]
