# Generated by Django 5.1.5 on 2026-06-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_detallepedido_precio_extra_salsa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos_img/'),
        ),
    ]
