# Generated by Django 5.1.5 on 2026-06-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_producto_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.AddField(
            model_name='producto',
            name='orden',
            field=models.IntegerField(default=0, help_text='Posición en el menú (1 va primero, 2 después, etc.)'),
        ),
    ]
