# Generated by Django 5.1.3 on 2026-06-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_producto_options_producto_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buffet_habilitado', models.BooleanField(default=True, verbose_name='¿Buffet Habilitado?')),
            ],
            options={
                'verbose_name_plural': 'Configuración',
            },
        ),
    ]
