# Generated by Django 4.2.30 on 2026-09-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_rapido',
            field=models.CharField(blank=True, help_text='Ej: 114 (Gaseosa), 216 (Milanesa)', max_length=20, null=True),
        ),
    ]
